# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-22 16:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('takeout', '0002_delete_test'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commodity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=30)),
                ('prize', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=30)),
                ('password', models.CharField(default='', max_length=16)),
                ('address', models.CharField(default='', max_length=1000)),
                ('outcome', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.IntegerField()),
                ('amount', models.FloatField()),
                ('orderTime', models.DateTimeField(auto_now_add=True)),
                ('commodity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='takeout.Commodity')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='takeout.Customer')),
            ],
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=30)),
                ('address', models.CharField(default='', max_length=1000)),
                ('income', models.FloatField()),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='takeout.Restaurant'),
        ),
        migrations.AddField(
            model_name='commodity',
            name='belong',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='takeout.Restaurant'),
        ),
    ]
